name: demo_guia_sxd
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6 # Cambiada a la versiÃ³n compatible
  provider: ^6.0.0
  flutter_secure_storage: ^7.0.0
  json_annotation: ^4.8.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.1.0
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
